### PR TITLE
Rewrite of the entire script

### PR DESCRIPTION
**Pull request by TheAio**
Made it easier to implement extentions and introduced keybindings. Just start typing to write any command,
press the arrow up to run the last command again or press C to run shortcuts, plugins and hardcoded extra features

### CODE REVIEW

**Comment by DevilishDawn431** [comment]
well that was unexpected, thanks alot!
how could I repay you?

**Comment by TheAio** [comment]
No need to pay me, that's the beautiful part of things being open source. Just make sure to credit me properly

**Comment by DevilishDawn431** [comment]
ok, also i wrote the credit in the commit message

**Comment by DevilishDawn431** [comment]
I also credited you in the description, just to be safe

**Pull request merged**
